// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.timer.ZeekrNumberPicker;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrTimerGroupLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrNumberPicker zeekrNumberPicker;

  @NonNull
  public final ZeekrNumberPicker zeekrNumberPicker2;

  private ZeekrTimerGroupLayoutBinding(@NonNull View rootView,
      @NonNull ZeekrNumberPicker zeekrNumberPicker, @NonNull ZeekrNumberPicker zeekrNumberPicker2) {
    this.rootView = rootView;
    this.zeekrNumberPicker = zeekrNumberPicker;
    this.zeekrNumberPicker2 = zeekrNumberPicker2;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrTimerGroupLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_timer_group_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrTimerGroupLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_number_picker;
      ZeekrNumberPicker zeekrNumberPicker = ViewBindings.findChildViewById(rootView, id);
      if (zeekrNumberPicker == null) {
        break missingId;
      }

      id = R.id.zeekr_number_picker2;
      ZeekrNumberPicker zeekrNumberPicker2 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrNumberPicker2 == null) {
        break missingId;
      }

      return new ZeekrTimerGroupLayoutBinding(rootView, zeekrNumberPicker, zeekrNumberPicker2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
