// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;

public final class ZeekrPoiButtonShadowLayoutBinding implements ViewBinding {
  @NonNull
  private final ImageView rootView;

  @NonNull
  public final ImageView zeekrPoiShadowId;

  private ZeekrPoiButtonShadowLayoutBinding(@NonNull ImageView rootView,
      @NonNull ImageView zeekrPoiShadowId) {
    this.rootView = rootView;
    this.zeekrPoiShadowId = zeekrPoiShadowId;
  }

  @Override
  @NonNull
  public ImageView getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrPoiButtonShadowLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrPoiButtonShadowLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_poi_button_shadow_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrPoiButtonShadowLayoutBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    ImageView zeekrPoiShadowId = (ImageView) rootView;

    return new ZeekrPoiButtonShadowLayoutBinding((ImageView) rootView, zeekrPoiShadowId);
  }
}
