// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrRailViewLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final Flow zeekrRailGroupFlow;

  @NonNull
  public final View zeekrRailViewDivider;

  @NonNull
  public final MaterialCardView zeekrRailViewIndicator;

  private ZeekrRailViewLayoutBinding(@NonNull View rootView, @NonNull Flow zeekrRailGroupFlow,
      @NonNull View zeekrRailViewDivider, @NonNull MaterialCardView zeekrRailViewIndicator) {
    this.rootView = rootView;
    this.zeekrRailGroupFlow = zeekrRailGroupFlow;
    this.zeekrRailViewDivider = zeekrRailViewDivider;
    this.zeekrRailViewIndicator = zeekrRailViewIndicator;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrRailViewLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_rail_view_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrRailViewLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_rail_group_flow;
      Flow zeekrRailGroupFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRailGroupFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_rail_view_divider;
      View zeekrRailViewDivider = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRailViewDivider == null) {
        break missingId;
      }

      id = R.id.zeekr_rail_view_indicator;
      MaterialCardView zeekrRailViewIndicator = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRailViewIndicator == null) {
        break missingId;
      }

      return new ZeekrRailViewLayoutBinding(rootView, zeekrRailGroupFlow, zeekrRailViewDivider,
          zeekrRailViewIndicator);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
