// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrSearchBarLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final MaterialCardView cardView;

  @NonNull
  public final LinearLayout layoutSearchBar;

  @NonNull
  public final ImageView searchBarClose;

  @NonNull
  public final EditText searchBarEdit;

  @NonNull
  public final TextView searchBarErrorText;

  @NonNull
  public final ImageView searchBarSearch;

  @NonNull
  public final ImageView searchBarShowPass;

  private ZeekrSearchBarLayoutBinding(@NonNull View rootView, @NonNull MaterialCardView cardView,
      @NonNull LinearLayout layoutSearchBar, @NonNull ImageView searchBarClose,
      @NonNull EditText searchBarEdit, @NonNull TextView searchBarErrorText,
      @NonNull ImageView searchBarSearch, @NonNull ImageView searchBarShowPass) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.layoutSearchBar = layoutSearchBar;
    this.searchBarClose = searchBarClose;
    this.searchBarEdit = searchBarEdit;
    this.searchBarErrorText = searchBarErrorText;
    this.searchBarSearch = searchBarSearch;
    this.searchBarShowPass = searchBarShowPass;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrSearchBarLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_search_bar_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrSearchBarLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.card_view;
      MaterialCardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.layout_search_bar;
      LinearLayout layoutSearchBar = ViewBindings.findChildViewById(rootView, id);
      if (layoutSearchBar == null) {
        break missingId;
      }

      id = R.id.search_bar_close;
      ImageView searchBarClose = ViewBindings.findChildViewById(rootView, id);
      if (searchBarClose == null) {
        break missingId;
      }

      id = R.id.search_bar_edit;
      EditText searchBarEdit = ViewBindings.findChildViewById(rootView, id);
      if (searchBarEdit == null) {
        break missingId;
      }

      id = R.id.search_bar_error_text;
      TextView searchBarErrorText = ViewBindings.findChildViewById(rootView, id);
      if (searchBarErrorText == null) {
        break missingId;
      }

      id = R.id.search_bar_search;
      ImageView searchBarSearch = ViewBindings.findChildViewById(rootView, id);
      if (searchBarSearch == null) {
        break missingId;
      }

      id = R.id.search_bar_show_pass;
      ImageView searchBarShowPass = ViewBindings.findChildViewById(rootView, id);
      if (searchBarShowPass == null) {
        break missingId;
      }

      return new ZeekrSearchBarLayoutBinding(rootView, cardView, layoutSearchBar, searchBarClose,
          searchBarEdit, searchBarErrorText, searchBarSearch, searchBarShowPass);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
