// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.motion.widget.MotionLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.ripple.ZeekrRipple;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrRippleVoiceLayoutBinding implements ViewBinding {
  @NonNull
  private final MotionLayout rootView;

  @NonNull
  public final ZeekrRipple zeekrRippleDynamic;

  private ZeekrRippleVoiceLayoutBinding(@NonNull MotionLayout rootView,
      @NonNull ZeekrRipple zeekrRippleDynamic) {
    this.rootView = rootView;
    this.zeekrRippleDynamic = zeekrRippleDynamic;
  }

  @Override
  @NonNull
  public MotionLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrRippleVoiceLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrRippleVoiceLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_ripple_voice_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrRippleVoiceLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_ripple_dynamic;
      ZeekrRipple zeekrRippleDynamic = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRippleDynamic == null) {
        break missingId;
      }

      return new ZeekrRippleVoiceLayoutBinding((MotionLayout) rootView, zeekrRippleDynamic);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
