// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.motion.widget.MotionLayout;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.imageview.ShapeableImageView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrSectionSliderLayoutBinding implements ViewBinding {
  @NonNull
  private final MotionLayout rootView;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle1;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle10;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle2;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle3;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle4;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle5;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle6;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle7;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle8;

  @NonNull
  public final ShapeableImageView zeekrSectionSliderCircle9;

  @NonNull
  public final Flow zeekrSectionSliderFlow;

  @NonNull
  public final MaterialCardView zeekrSectionSliderThumb;

  @NonNull
  public final Guideline zeekrSectionSliderTrackGuideline;

  private ZeekrSectionSliderLayoutBinding(@NonNull MotionLayout rootView,
      @NonNull ShapeableImageView zeekrSectionSliderCircle1,
      @NonNull ShapeableImageView zeekrSectionSliderCircle10,
      @NonNull ShapeableImageView zeekrSectionSliderCircle2,
      @NonNull ShapeableImageView zeekrSectionSliderCircle3,
      @NonNull ShapeableImageView zeekrSectionSliderCircle4,
      @NonNull ShapeableImageView zeekrSectionSliderCircle5,
      @NonNull ShapeableImageView zeekrSectionSliderCircle6,
      @NonNull ShapeableImageView zeekrSectionSliderCircle7,
      @NonNull ShapeableImageView zeekrSectionSliderCircle8,
      @NonNull ShapeableImageView zeekrSectionSliderCircle9, @NonNull Flow zeekrSectionSliderFlow,
      @NonNull MaterialCardView zeekrSectionSliderThumb,
      @NonNull Guideline zeekrSectionSliderTrackGuideline) {
    this.rootView = rootView;
    this.zeekrSectionSliderCircle1 = zeekrSectionSliderCircle1;
    this.zeekrSectionSliderCircle10 = zeekrSectionSliderCircle10;
    this.zeekrSectionSliderCircle2 = zeekrSectionSliderCircle2;
    this.zeekrSectionSliderCircle3 = zeekrSectionSliderCircle3;
    this.zeekrSectionSliderCircle4 = zeekrSectionSliderCircle4;
    this.zeekrSectionSliderCircle5 = zeekrSectionSliderCircle5;
    this.zeekrSectionSliderCircle6 = zeekrSectionSliderCircle6;
    this.zeekrSectionSliderCircle7 = zeekrSectionSliderCircle7;
    this.zeekrSectionSliderCircle8 = zeekrSectionSliderCircle8;
    this.zeekrSectionSliderCircle9 = zeekrSectionSliderCircle9;
    this.zeekrSectionSliderFlow = zeekrSectionSliderFlow;
    this.zeekrSectionSliderThumb = zeekrSectionSliderThumb;
    this.zeekrSectionSliderTrackGuideline = zeekrSectionSliderTrackGuideline;
  }

  @Override
  @NonNull
  public MotionLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrSectionSliderLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrSectionSliderLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_section_slider_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrSectionSliderLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_section_slider_circle1;
      ShapeableImageView zeekrSectionSliderCircle1 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle1 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle10;
      ShapeableImageView zeekrSectionSliderCircle10 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle10 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle2;
      ShapeableImageView zeekrSectionSliderCircle2 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle2 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle3;
      ShapeableImageView zeekrSectionSliderCircle3 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle3 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle4;
      ShapeableImageView zeekrSectionSliderCircle4 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle4 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle5;
      ShapeableImageView zeekrSectionSliderCircle5 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle5 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle6;
      ShapeableImageView zeekrSectionSliderCircle6 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle6 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle7;
      ShapeableImageView zeekrSectionSliderCircle7 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle7 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle8;
      ShapeableImageView zeekrSectionSliderCircle8 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle8 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_circle9;
      ShapeableImageView zeekrSectionSliderCircle9 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderCircle9 == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_flow;
      Flow zeekrSectionSliderFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_thumb;
      MaterialCardView zeekrSectionSliderThumb = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderThumb == null) {
        break missingId;
      }

      id = R.id.zeekr_section_slider_track_guideline;
      Guideline zeekrSectionSliderTrackGuideline = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSectionSliderTrackGuideline == null) {
        break missingId;
      }

      return new ZeekrSectionSliderLayoutBinding((MotionLayout) rootView, zeekrSectionSliderCircle1,
          zeekrSectionSliderCircle10, zeekrSectionSliderCircle2, zeekrSectionSliderCircle3,
          zeekrSectionSliderCircle4, zeekrSectionSliderCircle5, zeekrSectionSliderCircle6,
          zeekrSectionSliderCircle7, zeekrSectionSliderCircle8, zeekrSectionSliderCircle9,
          zeekrSectionSliderFlow, zeekrSectionSliderThumb, zeekrSectionSliderTrackGuideline);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
