// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.imageview.ShapeableImageView;
import com.google.android.material.textview.MaterialTextView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrStepperContentBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ShapeableImageView zeekrStepperAdd;

  @NonNull
  public final MaterialTextView zeekrStepperNumber;

  @NonNull
  public final ShapeableImageView zeekrStepperStroke;

  @NonNull
  public final MaterialTextView zeekrStepperUnit;

  private ZeekrStepperContentBinding(@NonNull View rootView,
      @NonNull ShapeableImageView zeekrStepperAdd, @NonNull MaterialTextView zeekrStepperNumber,
      @NonNull ShapeableImageView zeekrStepperStroke, @NonNull MaterialTextView zeekrStepperUnit) {
    this.rootView = rootView;
    this.zeekrStepperAdd = zeekrStepperAdd;
    this.zeekrStepperNumber = zeekrStepperNumber;
    this.zeekrStepperStroke = zeekrStepperStroke;
    this.zeekrStepperUnit = zeekrStepperUnit;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrStepperContentBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_stepper_content, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrStepperContentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_stepper_add;
      ShapeableImageView zeekrStepperAdd = ViewBindings.findChildViewById(rootView, id);
      if (zeekrStepperAdd == null) {
        break missingId;
      }

      id = R.id.zeekr_stepper_number;
      MaterialTextView zeekrStepperNumber = ViewBindings.findChildViewById(rootView, id);
      if (zeekrStepperNumber == null) {
        break missingId;
      }

      id = R.id.zeekr_stepper_stroke;
      ShapeableImageView zeekrStepperStroke = ViewBindings.findChildViewById(rootView, id);
      if (zeekrStepperStroke == null) {
        break missingId;
      }

      id = R.id.zeekr_stepper_unit;
      MaterialTextView zeekrStepperUnit = ViewBindings.findChildViewById(rootView, id);
      if (zeekrStepperUnit == null) {
        break missingId;
      }

      return new ZeekrStepperContentBinding(rootView, zeekrStepperAdd, zeekrStepperNumber,
          zeekrStepperStroke, zeekrStepperUnit);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
