// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextSwitcher;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.button.ZeekrToggleButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrToggleSwitchBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrToggleButton zeekrToggleButton;

  @NonNull
  public final TextSwitcher zeekrToggleTextSwitch;

  private ZeekrToggleSwitchBinding(@NonNull View rootView,
      @NonNull ZeekrToggleButton zeekrToggleButton, @NonNull TextSwitcher zeekrToggleTextSwitch) {
    this.rootView = rootView;
    this.zeekrToggleButton = zeekrToggleButton;
    this.zeekrToggleTextSwitch = zeekrToggleTextSwitch;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrToggleSwitchBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_toggle_switch, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrToggleSwitchBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_toggle_button;
      ZeekrToggleButton zeekrToggleButton = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleButton == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_textSwitch;
      TextSwitcher zeekrToggleTextSwitch = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleTextSwitch == null) {
        break missingId;
      }

      return new ZeekrToggleSwitchBinding(rootView, zeekrToggleButton, zeekrToggleTextSwitch);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
