// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrLeftMenuFirstBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final Flow zeekrLeftMenuGroupFlow;

  @NonNull
  public final Guideline zeekrLeftMenuGuidelineBottom;

  @NonNull
  public final Guideline zeekrLeftMenuGuidelineTop;

  @NonNull
  public final View zeekrLeftMenuViewDivider;

  @NonNull
  public final MaterialCardView zeekrLeftMenuViewIndicator;

  private ZeekrLeftMenuFirstBinding(@NonNull View rootView, @NonNull Flow zeekrLeftMenuGroupFlow,
      @NonNull Guideline zeekrLeftMenuGuidelineBottom, @NonNull Guideline zeekrLeftMenuGuidelineTop,
      @NonNull View zeekrLeftMenuViewDivider,
      @NonNull MaterialCardView zeekrLeftMenuViewIndicator) {
    this.rootView = rootView;
    this.zeekrLeftMenuGroupFlow = zeekrLeftMenuGroupFlow;
    this.zeekrLeftMenuGuidelineBottom = zeekrLeftMenuGuidelineBottom;
    this.zeekrLeftMenuGuidelineTop = zeekrLeftMenuGuidelineTop;
    this.zeekrLeftMenuViewDivider = zeekrLeftMenuViewDivider;
    this.zeekrLeftMenuViewIndicator = zeekrLeftMenuViewIndicator;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrLeftMenuFirstBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_left_menu_first, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrLeftMenuFirstBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_left_menu_group_flow;
      Flow zeekrLeftMenuGroupFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuGroupFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_guideline_bottom;
      Guideline zeekrLeftMenuGuidelineBottom = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuGuidelineBottom == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_guideline_top;
      Guideline zeekrLeftMenuGuidelineTop = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuGuidelineTop == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_view_divider;
      View zeekrLeftMenuViewDivider = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuViewDivider == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_view_indicator;
      MaterialCardView zeekrLeftMenuViewIndicator = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuViewIndicator == null) {
        break missingId;
      }

      return new ZeekrLeftMenuFirstBinding(rootView, zeekrLeftMenuGroupFlow,
          zeekrLeftMenuGuidelineBottom, zeekrLeftMenuGuidelineTop, zeekrLeftMenuViewDivider,
          zeekrLeftMenuViewIndicator);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
