// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.zeekr.component.R;
import com.zeekr.component.dialog.ZeekrDialogLayout;
import java.lang.NullPointerException;
import java.lang.Override;

public final class ZeekrDialogCommonLayoutBinding implements ViewBinding {
  @NonNull
  private final ZeekrDialogLayout rootView;

  private ZeekrDialogCommonLayoutBinding(@NonNull ZeekrDialogLayout rootView) {
    this.rootView = rootView;
  }

  @Override
  @NonNull
  public ZeekrDialogLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogCommonLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrDialogCommonLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_dialog_common_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrDialogCommonLayoutBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    return new ZeekrDialogCommonLayoutBinding((ZeekrDialogLayout) rootView);
  }
}
