// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;

public final class ZeekrCheckContentBinding implements ViewBinding {
  @NonNull
  private final ImageView rootView;

  @NonNull
  public final ImageView zeekrCheckImg;

  private ZeekrCheckContentBinding(@NonNull ImageView rootView, @NonNull ImageView zeekrCheckImg) {
    this.rootView = rootView;
    this.zeekrCheckImg = zeekrCheckImg;
  }

  @Override
  @NonNull
  public ImageView getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrCheckContentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrCheckContentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_check_content, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrCheckContentBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    ImageView zeekrCheckImg = (ImageView) rootView;

    return new ZeekrCheckContentBinding((ImageView) rootView, zeekrCheckImg);
  }
}
