// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.button.ZeekrButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogLayoutMergeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Flow zeekrDialogButtonFlow;

  @NonNull
  public final Guideline zeekrDialogButtonGuidelineBottom;

  @NonNull
  public final FrameLayout zeekrDialogCenterLayout;

  @NonNull
  public final ConstraintLayout zeekrDialogCustomLayout;

  @NonNull
  public final ImageView zeekrDialogEditClose;

  @NonNull
  public final ZeekrButton zeekrDialogNegativeButton;

  @NonNull
  public final ZeekrButton zeekrDialogNeutralButton;

  @NonNull
  public final ZeekrButton zeekrDialogPositiveButton;

  @NonNull
  public final TextView zeekrDialogTitle;

  @NonNull
  public final Guideline zeekrDialogTitleGuidelineTop;

  private ZeekrDialogLayoutMergeBinding(@NonNull ConstraintLayout rootView,
      @NonNull Flow zeekrDialogButtonFlow, @NonNull Guideline zeekrDialogButtonGuidelineBottom,
      @NonNull FrameLayout zeekrDialogCenterLayout,
      @NonNull ConstraintLayout zeekrDialogCustomLayout, @NonNull ImageView zeekrDialogEditClose,
      @NonNull ZeekrButton zeekrDialogNegativeButton, @NonNull ZeekrButton zeekrDialogNeutralButton,
      @NonNull ZeekrButton zeekrDialogPositiveButton, @NonNull TextView zeekrDialogTitle,
      @NonNull Guideline zeekrDialogTitleGuidelineTop) {
    this.rootView = rootView;
    this.zeekrDialogButtonFlow = zeekrDialogButtonFlow;
    this.zeekrDialogButtonGuidelineBottom = zeekrDialogButtonGuidelineBottom;
    this.zeekrDialogCenterLayout = zeekrDialogCenterLayout;
    this.zeekrDialogCustomLayout = zeekrDialogCustomLayout;
    this.zeekrDialogEditClose = zeekrDialogEditClose;
    this.zeekrDialogNegativeButton = zeekrDialogNegativeButton;
    this.zeekrDialogNeutralButton = zeekrDialogNeutralButton;
    this.zeekrDialogPositiveButton = zeekrDialogPositiveButton;
    this.zeekrDialogTitle = zeekrDialogTitle;
    this.zeekrDialogTitleGuidelineTop = zeekrDialogTitleGuidelineTop;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogLayoutMergeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrDialogLayoutMergeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_dialog_layout_merge, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrDialogLayoutMergeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_dialog_button_flow;
      Flow zeekrDialogButtonFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogButtonFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_button_guideline_bottom;
      Guideline zeekrDialogButtonGuidelineBottom = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogButtonGuidelineBottom == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_center_layout;
      FrameLayout zeekrDialogCenterLayout = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogCenterLayout == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_custom_layout;
      ConstraintLayout zeekrDialogCustomLayout = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogCustomLayout == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_edit_close;
      ImageView zeekrDialogEditClose = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogEditClose == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_negative_button;
      ZeekrButton zeekrDialogNegativeButton = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogNegativeButton == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_neutral_button;
      ZeekrButton zeekrDialogNeutralButton = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogNeutralButton == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_positive_button;
      ZeekrButton zeekrDialogPositiveButton = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogPositiveButton == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_title;
      TextView zeekrDialogTitle = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogTitle == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_title_guideline_top;
      Guideline zeekrDialogTitleGuidelineTop = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogTitleGuidelineTop == null) {
        break missingId;
      }

      return new ZeekrDialogLayoutMergeBinding((ConstraintLayout) rootView, zeekrDialogButtonFlow,
          zeekrDialogButtonGuidelineBottom, zeekrDialogCenterLayout, zeekrDialogCustomLayout,
          zeekrDialogEditClose, zeekrDialogNegativeButton, zeekrDialogNeutralButton,
          zeekrDialogPositiveButton, zeekrDialogTitle, zeekrDialogTitleGuidelineTop);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
