// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.motion.widget.MotionLayout;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.imageview.ShapeableImageView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrLevelSliderLayoutBinding implements ViewBinding {
  @NonNull
  private final MotionLayout rootView;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle1;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle10;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle11;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle12;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle13;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle2;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle3;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle4;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle5;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle6;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle7;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle8;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderCircle9;

  @NonNull
  public final Flow zeekrLevelSliderFlow;

  @NonNull
  public final MaterialCardView zeekrLevelSliderThumb;

  @NonNull
  public final ShapeableImageView zeekrLevelSliderTrack;

  @NonNull
  public final Guideline zeekrLevelSliderTrackGuideline;

  private ZeekrLevelSliderLayoutBinding(@NonNull MotionLayout rootView,
      @NonNull ShapeableImageView zeekrLevelSliderCircle1,
      @NonNull ShapeableImageView zeekrLevelSliderCircle10,
      @NonNull ShapeableImageView zeekrLevelSliderCircle11,
      @NonNull ShapeableImageView zeekrLevelSliderCircle12,
      @NonNull ShapeableImageView zeekrLevelSliderCircle13,
      @NonNull ShapeableImageView zeekrLevelSliderCircle2,
      @NonNull ShapeableImageView zeekrLevelSliderCircle3,
      @NonNull ShapeableImageView zeekrLevelSliderCircle4,
      @NonNull ShapeableImageView zeekrLevelSliderCircle5,
      @NonNull ShapeableImageView zeekrLevelSliderCircle6,
      @NonNull ShapeableImageView zeekrLevelSliderCircle7,
      @NonNull ShapeableImageView zeekrLevelSliderCircle8,
      @NonNull ShapeableImageView zeekrLevelSliderCircle9, @NonNull Flow zeekrLevelSliderFlow,
      @NonNull MaterialCardView zeekrLevelSliderThumb,
      @NonNull ShapeableImageView zeekrLevelSliderTrack,
      @NonNull Guideline zeekrLevelSliderTrackGuideline) {
    this.rootView = rootView;
    this.zeekrLevelSliderCircle1 = zeekrLevelSliderCircle1;
    this.zeekrLevelSliderCircle10 = zeekrLevelSliderCircle10;
    this.zeekrLevelSliderCircle11 = zeekrLevelSliderCircle11;
    this.zeekrLevelSliderCircle12 = zeekrLevelSliderCircle12;
    this.zeekrLevelSliderCircle13 = zeekrLevelSliderCircle13;
    this.zeekrLevelSliderCircle2 = zeekrLevelSliderCircle2;
    this.zeekrLevelSliderCircle3 = zeekrLevelSliderCircle3;
    this.zeekrLevelSliderCircle4 = zeekrLevelSliderCircle4;
    this.zeekrLevelSliderCircle5 = zeekrLevelSliderCircle5;
    this.zeekrLevelSliderCircle6 = zeekrLevelSliderCircle6;
    this.zeekrLevelSliderCircle7 = zeekrLevelSliderCircle7;
    this.zeekrLevelSliderCircle8 = zeekrLevelSliderCircle8;
    this.zeekrLevelSliderCircle9 = zeekrLevelSliderCircle9;
    this.zeekrLevelSliderFlow = zeekrLevelSliderFlow;
    this.zeekrLevelSliderThumb = zeekrLevelSliderThumb;
    this.zeekrLevelSliderTrack = zeekrLevelSliderTrack;
    this.zeekrLevelSliderTrackGuideline = zeekrLevelSliderTrackGuideline;
  }

  @Override
  @NonNull
  public MotionLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrLevelSliderLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrLevelSliderLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_level_slider_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrLevelSliderLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_level_slider_circle1;
      ShapeableImageView zeekrLevelSliderCircle1 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle1 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle10;
      ShapeableImageView zeekrLevelSliderCircle10 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle10 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle11;
      ShapeableImageView zeekrLevelSliderCircle11 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle11 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle12;
      ShapeableImageView zeekrLevelSliderCircle12 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle12 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle13;
      ShapeableImageView zeekrLevelSliderCircle13 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle13 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle2;
      ShapeableImageView zeekrLevelSliderCircle2 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle2 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle3;
      ShapeableImageView zeekrLevelSliderCircle3 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle3 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle4;
      ShapeableImageView zeekrLevelSliderCircle4 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle4 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle5;
      ShapeableImageView zeekrLevelSliderCircle5 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle5 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle6;
      ShapeableImageView zeekrLevelSliderCircle6 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle6 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle7;
      ShapeableImageView zeekrLevelSliderCircle7 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle7 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle8;
      ShapeableImageView zeekrLevelSliderCircle8 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle8 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_circle9;
      ShapeableImageView zeekrLevelSliderCircle9 = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderCircle9 == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_flow;
      Flow zeekrLevelSliderFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_thumb;
      MaterialCardView zeekrLevelSliderThumb = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderThumb == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_track;
      ShapeableImageView zeekrLevelSliderTrack = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderTrack == null) {
        break missingId;
      }

      id = R.id.zeekr_level_slider_track_guideline;
      Guideline zeekrLevelSliderTrackGuideline = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLevelSliderTrackGuideline == null) {
        break missingId;
      }

      return new ZeekrLevelSliderLayoutBinding((MotionLayout) rootView, zeekrLevelSliderCircle1,
          zeekrLevelSliderCircle10, zeekrLevelSliderCircle11, zeekrLevelSliderCircle12,
          zeekrLevelSliderCircle13, zeekrLevelSliderCircle2, zeekrLevelSliderCircle3,
          zeekrLevelSliderCircle4, zeekrLevelSliderCircle5, zeekrLevelSliderCircle6,
          zeekrLevelSliderCircle7, zeekrLevelSliderCircle8, zeekrLevelSliderCircle9,
          zeekrLevelSliderFlow, zeekrLevelSliderThumb, zeekrLevelSliderTrack,
          zeekrLevelSliderTrackGuideline);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
