// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrLeftMenuSecondDefaultItemBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final MaterialCardView zeekrLeftMenuItemCard;

  @NonNull
  public final ImageView zeekrLeftMenuItemIcon;

  @NonNull
  public final TextView zeekrLeftMenuItemText;

  private ZeekrLeftMenuSecondDefaultItemBinding(@NonNull MaterialCardView rootView,
      @NonNull MaterialCardView zeekrLeftMenuItemCard, @NonNull ImageView zeekrLeftMenuItemIcon,
      @NonNull TextView zeekrLeftMenuItemText) {
    this.rootView = rootView;
    this.zeekrLeftMenuItemCard = zeekrLeftMenuItemCard;
    this.zeekrLeftMenuItemIcon = zeekrLeftMenuItemIcon;
    this.zeekrLeftMenuItemText = zeekrLeftMenuItemText;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrLeftMenuSecondDefaultItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrLeftMenuSecondDefaultItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_left_menu_second_default_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrLeftMenuSecondDefaultItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      MaterialCardView zeekrLeftMenuItemCard = (MaterialCardView) rootView;

      id = R.id.zeekr_left_menu_item_icon;
      ImageView zeekrLeftMenuItemIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuItemIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_item_text;
      TextView zeekrLeftMenuItemText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuItemText == null) {
        break missingId;
      }

      return new ZeekrLeftMenuSecondDefaultItemBinding((MaterialCardView) rootView,
          zeekrLeftMenuItemCard, zeekrLeftMenuItemIcon, zeekrLeftMenuItemText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
