// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.selection.ZeekrSwitchText;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrSwitchLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final FrameLayout switchButtonContainer;

  @NonNull
  public final ImageView zeekrSwitchIcon;

  @NonNull
  public final ZeekrSwitchText zeekrSwitchText;

  @NonNull
  public final TextView zeekrSwitchTip;

  @NonNull
  public final View zeekrSwitchTrackShadow;

  private ZeekrSwitchLayoutBinding(@NonNull View rootView,
      @NonNull FrameLayout switchButtonContainer, @NonNull ImageView zeekrSwitchIcon,
      @NonNull ZeekrSwitchText zeekrSwitchText, @NonNull TextView zeekrSwitchTip,
      @NonNull View zeekrSwitchTrackShadow) {
    this.rootView = rootView;
    this.switchButtonContainer = switchButtonContainer;
    this.zeekrSwitchIcon = zeekrSwitchIcon;
    this.zeekrSwitchText = zeekrSwitchText;
    this.zeekrSwitchTip = zeekrSwitchTip;
    this.zeekrSwitchTrackShadow = zeekrSwitchTrackShadow;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrSwitchLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_switch_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrSwitchLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.switchButtonContainer;
      FrameLayout switchButtonContainer = ViewBindings.findChildViewById(rootView, id);
      if (switchButtonContainer == null) {
        break missingId;
      }

      id = R.id.zeekr_switch_icon;
      ImageView zeekrSwitchIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSwitchIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_switch_text;
      ZeekrSwitchText zeekrSwitchText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSwitchText == null) {
        break missingId;
      }

      id = R.id.zeekr_switch_tip;
      TextView zeekrSwitchTip = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSwitchTip == null) {
        break missingId;
      }

      id = R.id.zeekr_switch_track_shadow;
      View zeekrSwitchTrackShadow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSwitchTrackShadow == null) {
        break missingId;
      }

      return new ZeekrSwitchLayoutBinding(rootView, switchButtonContainer, zeekrSwitchIcon,
          zeekrSwitchText, zeekrSwitchTip, zeekrSwitchTrackShadow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
