// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.webview.ZeekrWebView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogCustomWebviewLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrWebView zeekrDialogWebView;

  private ZeekrDialogCustomWebviewLayoutBinding(@NonNull View rootView,
      @NonNull ZeekrWebView zeekrDialogWebView) {
    this.rootView = rootView;
    this.zeekrDialogWebView = zeekrDialogWebView;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogCustomWebviewLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_dialog_custom_webview_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrDialogCustomWebviewLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_dialog_web_view;
      ZeekrWebView zeekrDialogWebView = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogWebView == null) {
        break missingId;
      }

      return new ZeekrDialogCustomWebviewLayoutBinding(rootView, zeekrDialogWebView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
