// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrLeftMenuSecondBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final MaterialCardView zeekrLeftMenuCardView;

  @NonNull
  public final Flow zeekrLeftMenuGroupFlow;

  private ZeekrLeftMenuSecondBinding(@NonNull View rootView,
      @NonNull MaterialCardView zeekrLeftMenuCardView, @NonNull Flow zeekrLeftMenuGroupFlow) {
    this.rootView = rootView;
    this.zeekrLeftMenuCardView = zeekrLeftMenuCardView;
    this.zeekrLeftMenuGroupFlow = zeekrLeftMenuGroupFlow;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrLeftMenuSecondBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_left_menu_second, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrLeftMenuSecondBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_left_menu_card_view;
      MaterialCardView zeekrLeftMenuCardView = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuCardView == null) {
        break missingId;
      }

      id = R.id.zeekr_left_menu_group_flow;
      Flow zeekrLeftMenuGroupFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrLeftMenuGroupFlow == null) {
        break missingId;
      }

      return new ZeekrLeftMenuSecondBinding(rootView, zeekrLeftMenuCardView,
          zeekrLeftMenuGroupFlow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
