// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.loading.ZeekrLoadingView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrRefreshClassicsHeaderBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrLoadingView zeekrCircleLoading;

  @NonNull
  public final LinearLayout zeekrRefreshContainer;

  @NonNull
  public final TextView zeekrRefreshText;

  private ZeekrRefreshClassicsHeaderBinding(@NonNull View rootView,
      @NonNull ZeekrLoadingView zeekrCircleLoading, @NonNull LinearLayout zeekrRefreshContainer,
      @NonNull TextView zeekrRefreshText) {
    this.rootView = rootView;
    this.zeekrCircleLoading = zeekrCircleLoading;
    this.zeekrRefreshContainer = zeekrRefreshContainer;
    this.zeekrRefreshText = zeekrRefreshText;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrRefreshClassicsHeaderBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_refresh_classics_header, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrRefreshClassicsHeaderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_circle_loading;
      ZeekrLoadingView zeekrCircleLoading = ViewBindings.findChildViewById(rootView, id);
      if (zeekrCircleLoading == null) {
        break missingId;
      }

      id = R.id.zeekr_refresh_container;
      LinearLayout zeekrRefreshContainer = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRefreshContainer == null) {
        break missingId;
      }

      id = R.id.zeekr_refresh_text;
      TextView zeekrRefreshText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRefreshText == null) {
        break missingId;
      }

      return new ZeekrRefreshClassicsHeaderBinding(rootView, zeekrCircleLoading,
          zeekrRefreshContainer, zeekrRefreshText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
