// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.timer.ZeekrNumberPicker;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogCustomTimerLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrNumberPicker zeekrNumberPicker;

  @NonNull
  public final TextView zeekrNumberPickerTip;

  private ZeekrDialogCustomTimerLayoutBinding(@NonNull View rootView,
      @NonNull ZeekrNumberPicker zeekrNumberPicker, @NonNull TextView zeekrNumberPickerTip) {
    this.rootView = rootView;
    this.zeekrNumberPicker = zeekrNumberPicker;
    this.zeekrNumberPickerTip = zeekrNumberPickerTip;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogCustomTimerLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_dialog_custom_timer_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrDialogCustomTimerLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_number_picker;
      ZeekrNumberPicker zeekrNumberPicker = ViewBindings.findChildViewById(rootView, id);
      if (zeekrNumberPicker == null) {
        break missingId;
      }

      id = R.id.zeekr_number_picker_tip;
      TextView zeekrNumberPickerTip = ViewBindings.findChildViewById(rootView, id);
      if (zeekrNumberPickerTip == null) {
        break missingId;
      }

      return new ZeekrDialogCustomTimerLayoutBinding(rootView, zeekrNumberPicker,
          zeekrNumberPickerTip);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
