// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrToggleMultiTextDefaultLayoutBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView zeekrToggleCardMultiLineContentTip;

  @NonNull
  public final TextView zeekrToggleCardMultiLineContentTitle;

  private ZeekrToggleMultiTextDefaultLayoutBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView zeekrToggleCardMultiLineContentTip,
      @NonNull TextView zeekrToggleCardMultiLineContentTitle) {
    this.rootView = rootView;
    this.zeekrToggleCardMultiLineContentTip = zeekrToggleCardMultiLineContentTip;
    this.zeekrToggleCardMultiLineContentTitle = zeekrToggleCardMultiLineContentTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrToggleMultiTextDefaultLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrToggleMultiTextDefaultLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_toggle_multi_text_default_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrToggleMultiTextDefaultLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_toggle_card_multi_line_content_tip;
      TextView zeekrToggleCardMultiLineContentTip = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleCardMultiLineContentTip == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_card_multi_line_content_title;
      TextView zeekrToggleCardMultiLineContentTitle = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleCardMultiLineContentTitle == null) {
        break missingId;
      }

      return new ZeekrToggleMultiTextDefaultLayoutBinding((ConstraintLayout) rootView,
          zeekrToggleCardMultiLineContentTip, zeekrToggleCardMultiLineContentTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
