// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.scroll.ZeekrScrollBar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogCustomSelectLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ZeekrScrollBar zeekrDialogScrollBar;

  @NonNull
  public final LinearLayout zeekrDialogSelectGroup;

  @NonNull
  public final NestedScrollView zeekrDialogSelectScroll;

  @NonNull
  public final TextView zeekrDialogSelectSubtitle;

  private ZeekrDialogCustomSelectLayoutBinding(@NonNull View rootView,
      @NonNull ZeekrScrollBar zeekrDialogScrollBar, @NonNull LinearLayout zeekrDialogSelectGroup,
      @NonNull NestedScrollView zeekrDialogSelectScroll,
      @NonNull TextView zeekrDialogSelectSubtitle) {
    this.rootView = rootView;
    this.zeekrDialogScrollBar = zeekrDialogScrollBar;
    this.zeekrDialogSelectGroup = zeekrDialogSelectGroup;
    this.zeekrDialogSelectScroll = zeekrDialogSelectScroll;
    this.zeekrDialogSelectSubtitle = zeekrDialogSelectSubtitle;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogCustomSelectLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_dialog_custom_select_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrDialogCustomSelectLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_dialog_scroll_bar;
      ZeekrScrollBar zeekrDialogScrollBar = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogScrollBar == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_select_group;
      LinearLayout zeekrDialogSelectGroup = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogSelectGroup == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_select_scroll;
      NestedScrollView zeekrDialogSelectScroll = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogSelectScroll == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_select_subtitle;
      TextView zeekrDialogSelectSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogSelectSubtitle == null) {
        break missingId;
      }

      return new ZeekrDialogCustomSelectLayoutBinding(rootView, zeekrDialogScrollBar,
          zeekrDialogSelectGroup, zeekrDialogSelectScroll, zeekrDialogSelectSubtitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
