// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrListItemContactExpandItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView zeekrListContactLayoutItemFav;

  @NonNull
  public final ImageView zeekrListContactLayoutItemIcon;

  @NonNull
  public final TextView zeekrListContactLayoutItemPhone;

  @NonNull
  public final TextView zeekrListContactLayoutItemText;

  private ZeekrListItemContactExpandItemBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView zeekrListContactLayoutItemFav,
      @NonNull ImageView zeekrListContactLayoutItemIcon,
      @NonNull TextView zeekrListContactLayoutItemPhone,
      @NonNull TextView zeekrListContactLayoutItemText) {
    this.rootView = rootView;
    this.zeekrListContactLayoutItemFav = zeekrListContactLayoutItemFav;
    this.zeekrListContactLayoutItemIcon = zeekrListContactLayoutItemIcon;
    this.zeekrListContactLayoutItemPhone = zeekrListContactLayoutItemPhone;
    this.zeekrListContactLayoutItemText = zeekrListContactLayoutItemText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrListItemContactExpandItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrListItemContactExpandItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_list_item_contact_expand_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrListItemContactExpandItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_list_contact_layout_item_fav;
      ImageView zeekrListContactLayoutItemFav = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLayoutItemFav == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_layout_item_icon;
      ImageView zeekrListContactLayoutItemIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLayoutItemIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_layout_item_phone;
      TextView zeekrListContactLayoutItemPhone = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLayoutItemPhone == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_layout_item_text;
      TextView zeekrListContactLayoutItemText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLayoutItemText == null) {
        break missingId;
      }

      return new ZeekrListItemContactExpandItemBinding((ConstraintLayout) rootView,
          zeekrListContactLayoutItemFav, zeekrListContactLayoutItemIcon,
          zeekrListContactLayoutItemPhone, zeekrListContactLayoutItemText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
