// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrSpinnerLayoutBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView zeekrSpinnerLayoutExpand;

  @NonNull
  public final ImageView zeekrSpinnerLayoutIcon;

  @NonNull
  public final TextView zeekrSpinnerLayoutName;

  private ZeekrSpinnerLayoutBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView zeekrSpinnerLayoutExpand, @NonNull ImageView zeekrSpinnerLayoutIcon,
      @NonNull TextView zeekrSpinnerLayoutName) {
    this.rootView = rootView;
    this.zeekrSpinnerLayoutExpand = zeekrSpinnerLayoutExpand;
    this.zeekrSpinnerLayoutIcon = zeekrSpinnerLayoutIcon;
    this.zeekrSpinnerLayoutName = zeekrSpinnerLayoutName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrSpinnerLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrSpinnerLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_spinner_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrSpinnerLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_spinner_layout_expand;
      ImageView zeekrSpinnerLayoutExpand = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerLayoutExpand == null) {
        break missingId;
      }

      id = R.id.zeekr_spinner_layout_icon;
      ImageView zeekrSpinnerLayoutIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerLayoutIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_spinner_layout_name;
      TextView zeekrSpinnerLayoutName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerLayoutName == null) {
        break missingId;
      }

      return new ZeekrSpinnerLayoutBinding((ConstraintLayout) rootView, zeekrSpinnerLayoutExpand,
          zeekrSpinnerLayoutIcon, zeekrSpinnerLayoutName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
