// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrListItemPhoneLayoutBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView zeekrListContactAvatar;

  @NonNull
  public final TextView zeekrListContactFirstName;

  @NonNull
  public final TextView zeekrListContactLastName;

  @NonNull
  public final TextView zeekrListContactPhone;

  @NonNull
  public final ImageView zeekrListPhoneLayoutDialState;

  @NonNull
  public final TextView zeekrListPhoneLayoutDialTime;

  @NonNull
  public final ImageView zeekrListShadow;

  private ZeekrListItemPhoneLayoutBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView zeekrListContactAvatar, @NonNull TextView zeekrListContactFirstName,
      @NonNull TextView zeekrListContactLastName, @NonNull TextView zeekrListContactPhone,
      @NonNull ImageView zeekrListPhoneLayoutDialState,
      @NonNull TextView zeekrListPhoneLayoutDialTime, @NonNull ImageView zeekrListShadow) {
    this.rootView = rootView;
    this.zeekrListContactAvatar = zeekrListContactAvatar;
    this.zeekrListContactFirstName = zeekrListContactFirstName;
    this.zeekrListContactLastName = zeekrListContactLastName;
    this.zeekrListContactPhone = zeekrListContactPhone;
    this.zeekrListPhoneLayoutDialState = zeekrListPhoneLayoutDialState;
    this.zeekrListPhoneLayoutDialTime = zeekrListPhoneLayoutDialTime;
    this.zeekrListShadow = zeekrListShadow;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrListItemPhoneLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrListItemPhoneLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_list_item_phone_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrListItemPhoneLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_list_contact_avatar;
      ImageView zeekrListContactAvatar = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactAvatar == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_first_name;
      TextView zeekrListContactFirstName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactFirstName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_last_name;
      TextView zeekrListContactLastName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLastName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_phone;
      TextView zeekrListContactPhone = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactPhone == null) {
        break missingId;
      }

      id = R.id.zeekr_list_phone_layout_dial_state;
      ImageView zeekrListPhoneLayoutDialState = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListPhoneLayoutDialState == null) {
        break missingId;
      }

      id = R.id.zeekr_list_phone_layout_dial_time;
      TextView zeekrListPhoneLayoutDialTime = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListPhoneLayoutDialTime == null) {
        break missingId;
      }

      id = R.id.zeekr_list_shadow;
      ImageView zeekrListShadow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListShadow == null) {
        break missingId;
      }

      return new ZeekrListItemPhoneLayoutBinding((ConstraintLayout) rootView,
          zeekrListContactAvatar, zeekrListContactFirstName, zeekrListContactLastName,
          zeekrListContactPhone, zeekrListPhoneLayoutDialState, zeekrListPhoneLayoutDialTime,
          zeekrListShadow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
