// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.imageview.ShapeableImageView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrRailViewItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ShapeableImageView zeekrRailItemIcon;

  @NonNull
  public final TextView zeekrRailItemText;

  private ZeekrRailViewItemBinding(@NonNull ConstraintLayout rootView,
      @NonNull ShapeableImageView zeekrRailItemIcon, @NonNull TextView zeekrRailItemText) {
    this.rootView = rootView;
    this.zeekrRailItemIcon = zeekrRailItemIcon;
    this.zeekrRailItemText = zeekrRailItemText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrRailViewItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrRailViewItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_rail_view_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrRailViewItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_rail_item_icon;
      ShapeableImageView zeekrRailItemIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRailItemIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_rail_item_text;
      TextView zeekrRailItemText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrRailItemText == null) {
        break missingId;
      }

      return new ZeekrRailViewItemBinding((ConstraintLayout) rootView, zeekrRailItemIcon,
          zeekrRailItemText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
