// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textview.MaterialTextView;
import com.zeekr.component.R;
import com.zeekr.component.scroll.ZeekrScrollBar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogScrollTextLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final MaterialTextView zeekrDialogConfirmContentText;

  @NonNull
  public final NestedScrollView zeekrDialogConfirmScroll;

  @NonNull
  public final ZeekrScrollBar zeekrDialogScrollBar;

  private ZeekrDialogScrollTextLayoutBinding(@NonNull View rootView,
      @NonNull MaterialTextView zeekrDialogConfirmContentText,
      @NonNull NestedScrollView zeekrDialogConfirmScroll,
      @NonNull ZeekrScrollBar zeekrDialogScrollBar) {
    this.rootView = rootView;
    this.zeekrDialogConfirmContentText = zeekrDialogConfirmContentText;
    this.zeekrDialogConfirmScroll = zeekrDialogConfirmScroll;
    this.zeekrDialogScrollBar = zeekrDialogScrollBar;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogScrollTextLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_dialog_scroll_text_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrDialogScrollTextLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_dialog_confirm_content_text;
      MaterialTextView zeekrDialogConfirmContentText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogConfirmContentText == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_confirm_scroll;
      NestedScrollView zeekrDialogConfirmScroll = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogConfirmScroll == null) {
        break missingId;
      }

      id = R.id.zeekr_dialog_scroll_bar;
      ZeekrScrollBar zeekrDialogScrollBar = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogScrollBar == null) {
        break missingId;
      }

      return new ZeekrDialogScrollTextLayoutBinding(rootView, zeekrDialogConfirmContentText,
          zeekrDialogConfirmScroll, zeekrDialogScrollBar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
