// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrListItemContactLayoutBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final FrameLayout zeekrListCardView;

  @NonNull
  public final ImageView zeekrListContactAvatar;

  @NonNull
  public final TextView zeekrListContactFirstName;

  @NonNull
  public final TextView zeekrListContactLastName;

  @NonNull
  public final ImageView zeekrListContactLayoutExpand;

  @NonNull
  public final TextView zeekrListContactPhone;

  @NonNull
  public final ConstraintLayout zeekrListItemContactBottom;

  @NonNull
  public final Flow zeekrListItemContactFlow;

  @NonNull
  public final ConstraintLayout zeekrListItemContactTop;

  @NonNull
  public final ImageView zeekrListShadow;

  private ZeekrListItemContactLayoutBinding(@NonNull FrameLayout rootView,
      @NonNull FrameLayout zeekrListCardView, @NonNull ImageView zeekrListContactAvatar,
      @NonNull TextView zeekrListContactFirstName, @NonNull TextView zeekrListContactLastName,
      @NonNull ImageView zeekrListContactLayoutExpand, @NonNull TextView zeekrListContactPhone,
      @NonNull ConstraintLayout zeekrListItemContactBottom, @NonNull Flow zeekrListItemContactFlow,
      @NonNull ConstraintLayout zeekrListItemContactTop, @NonNull ImageView zeekrListShadow) {
    this.rootView = rootView;
    this.zeekrListCardView = zeekrListCardView;
    this.zeekrListContactAvatar = zeekrListContactAvatar;
    this.zeekrListContactFirstName = zeekrListContactFirstName;
    this.zeekrListContactLastName = zeekrListContactLastName;
    this.zeekrListContactLayoutExpand = zeekrListContactLayoutExpand;
    this.zeekrListContactPhone = zeekrListContactPhone;
    this.zeekrListItemContactBottom = zeekrListItemContactBottom;
    this.zeekrListItemContactFlow = zeekrListItemContactFlow;
    this.zeekrListItemContactTop = zeekrListItemContactTop;
    this.zeekrListShadow = zeekrListShadow;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrListItemContactLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrListItemContactLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_list_item_contact_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrListItemContactLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      FrameLayout zeekrListCardView = (FrameLayout) rootView;

      id = R.id.zeekr_list_contact_avatar;
      ImageView zeekrListContactAvatar = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactAvatar == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_first_name;
      TextView zeekrListContactFirstName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactFirstName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_last_name;
      TextView zeekrListContactLastName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLastName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_layout_expand;
      ImageView zeekrListContactLayoutExpand = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLayoutExpand == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_phone;
      TextView zeekrListContactPhone = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactPhone == null) {
        break missingId;
      }

      id = R.id.zeekr_list_item_contact_bottom;
      ConstraintLayout zeekrListItemContactBottom = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListItemContactBottom == null) {
        break missingId;
      }

      id = R.id.zeekr_list_item_contact_flow;
      Flow zeekrListItemContactFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListItemContactFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_list_item_contact_top;
      ConstraintLayout zeekrListItemContactTop = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListItemContactTop == null) {
        break missingId;
      }

      id = R.id.zeekr_list_shadow;
      ImageView zeekrListShadow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListShadow == null) {
        break missingId;
      }

      return new ZeekrListItemContactLayoutBinding((FrameLayout) rootView, zeekrListCardView,
          zeekrListContactAvatar, zeekrListContactFirstName, zeekrListContactLastName,
          zeekrListContactLayoutExpand, zeekrListContactPhone, zeekrListItemContactBottom,
          zeekrListItemContactFlow, zeekrListItemContactTop, zeekrListShadow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
