// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrSpinnerItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout zeekrSpinnerItemConstraint;

  @NonNull
  public final ImageView zeekrSpinnerItemIcon;

  @NonNull
  public final TextView zeekrSpinnerItemName;

  @NonNull
  public final MaterialCardView zeekrSpinnerItemSelect;

  private ZeekrSpinnerItemBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout zeekrSpinnerItemConstraint, @NonNull ImageView zeekrSpinnerItemIcon,
      @NonNull TextView zeekrSpinnerItemName, @NonNull MaterialCardView zeekrSpinnerItemSelect) {
    this.rootView = rootView;
    this.zeekrSpinnerItemConstraint = zeekrSpinnerItemConstraint;
    this.zeekrSpinnerItemIcon = zeekrSpinnerItemIcon;
    this.zeekrSpinnerItemName = zeekrSpinnerItemName;
    this.zeekrSpinnerItemSelect = zeekrSpinnerItemSelect;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrSpinnerItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrSpinnerItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_spinner_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrSpinnerItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ConstraintLayout zeekrSpinnerItemConstraint = (ConstraintLayout) rootView;

      id = R.id.zeekr_spinner_item_icon;
      ImageView zeekrSpinnerItemIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerItemIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_spinner_item_name;
      TextView zeekrSpinnerItemName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerItemName == null) {
        break missingId;
      }

      id = R.id.zeekr_spinner_item_select;
      MaterialCardView zeekrSpinnerItemSelect = ViewBindings.findChildViewById(rootView, id);
      if (zeekrSpinnerItemSelect == null) {
        break missingId;
      }

      return new ZeekrSpinnerItemBinding((ConstraintLayout) rootView, zeekrSpinnerItemConstraint,
          zeekrSpinnerItemIcon, zeekrSpinnerItemName, zeekrSpinnerItemSelect);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
