// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import com.zeekr.component.button.ZeekrButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrToggleGroupLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final MaterialCardView zeekrToggleGroupCard;

  @NonNull
  public final Flow zeekrToggleGroupFlow;

  @NonNull
  public final Guideline zeekrToggleGuidelineBottom;

  @NonNull
  public final Guideline zeekrToggleGuidelineEnd;

  @NonNull
  public final Guideline zeekrToggleGuidelineStart;

  @NonNull
  public final Guideline zeekrToggleGuidelineTop;

  @NonNull
  public final ZeekrButton zeekrToggleSelectButton;

  private ZeekrToggleGroupLayoutBinding(@NonNull View rootView,
      @NonNull MaterialCardView zeekrToggleGroupCard, @NonNull Flow zeekrToggleGroupFlow,
      @NonNull Guideline zeekrToggleGuidelineBottom, @NonNull Guideline zeekrToggleGuidelineEnd,
      @NonNull Guideline zeekrToggleGuidelineStart, @NonNull Guideline zeekrToggleGuidelineTop,
      @NonNull ZeekrButton zeekrToggleSelectButton) {
    this.rootView = rootView;
    this.zeekrToggleGroupCard = zeekrToggleGroupCard;
    this.zeekrToggleGroupFlow = zeekrToggleGroupFlow;
    this.zeekrToggleGuidelineBottom = zeekrToggleGuidelineBottom;
    this.zeekrToggleGuidelineEnd = zeekrToggleGuidelineEnd;
    this.zeekrToggleGuidelineStart = zeekrToggleGuidelineStart;
    this.zeekrToggleGuidelineTop = zeekrToggleGuidelineTop;
    this.zeekrToggleSelectButton = zeekrToggleSelectButton;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrToggleGroupLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_toggle_group_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrToggleGroupLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_toggle_group_card;
      MaterialCardView zeekrToggleGroupCard = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGroupCard == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_group_flow;
      Flow zeekrToggleGroupFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGroupFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_guideline_bottom;
      Guideline zeekrToggleGuidelineBottom = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGuidelineBottom == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_guideline_end;
      Guideline zeekrToggleGuidelineEnd = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGuidelineEnd == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_guideline_start;
      Guideline zeekrToggleGuidelineStart = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGuidelineStart == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_guideline_top;
      Guideline zeekrToggleGuidelineTop = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleGuidelineTop == null) {
        break missingId;
      }

      id = R.id.zeekr_toggle_select_button;
      ZeekrButton zeekrToggleSelectButton = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToggleSelectButton == null) {
        break missingId;
      }

      return new ZeekrToggleGroupLayoutBinding(rootView, zeekrToggleGroupCard, zeekrToggleGroupFlow,
          zeekrToggleGuidelineBottom, zeekrToggleGuidelineEnd, zeekrToggleGuidelineStart,
          zeekrToggleGuidelineTop, zeekrToggleSelectButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
