// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrTabViewLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final Flow zeekrTabGroupFlow;

  @NonNull
  public final Guideline zeekrTabGuidelineLeft;

  @NonNull
  public final MaterialCardView zeekrTabViewIndicator;

  private ZeekrTabViewLayoutBinding(@NonNull View rootView, @NonNull Flow zeekrTabGroupFlow,
      @NonNull Guideline zeekrTabGuidelineLeft, @NonNull MaterialCardView zeekrTabViewIndicator) {
    this.rootView = rootView;
    this.zeekrTabGroupFlow = zeekrTabGroupFlow;
    this.zeekrTabGuidelineLeft = zeekrTabGuidelineLeft;
    this.zeekrTabViewIndicator = zeekrTabViewIndicator;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrTabViewLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_tab_view_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrTabViewLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_tab_group_flow;
      Flow zeekrTabGroupFlow = ViewBindings.findChildViewById(rootView, id);
      if (zeekrTabGroupFlow == null) {
        break missingId;
      }

      id = R.id.zeekr_tab_guideline_left;
      Guideline zeekrTabGuidelineLeft = ViewBindings.findChildViewById(rootView, id);
      if (zeekrTabGuidelineLeft == null) {
        break missingId;
      }

      id = R.id.zeekr_tab_view_indicator;
      MaterialCardView zeekrTabViewIndicator = ViewBindings.findChildViewById(rootView, id);
      if (zeekrTabViewIndicator == null) {
        break missingId;
      }

      return new ZeekrTabViewLayoutBinding(rootView, zeekrTabGroupFlow, zeekrTabGuidelineLeft,
          zeekrTabViewIndicator);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
