// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.google.android.material.imageview.ShapeableImageView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;

public final class ZeekrToggleExpandIconBinding implements ViewBinding {
  @NonNull
  private final ShapeableImageView rootView;

  private ZeekrToggleExpandIconBinding(@NonNull ShapeableImageView rootView) {
    this.rootView = rootView;
  }

  @Override
  @NonNull
  public ShapeableImageView getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrToggleExpandIconBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrToggleExpandIconBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_toggle_expand_icon, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrToggleExpandIconBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    return new ZeekrToggleExpandIconBinding((ShapeableImageView) rootView);
  }
}
