// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrListItemContactMergeBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView zeekrListContactAvatar;

  @NonNull
  public final TextView zeekrListContactFirstName;

  @NonNull
  public final TextView zeekrListContactLastName;

  @NonNull
  public final TextView zeekrListContactPhone;

  private ZeekrListItemContactMergeBinding(@NonNull View rootView,
      @NonNull ImageView zeekrListContactAvatar, @NonNull TextView zeekrListContactFirstName,
      @NonNull TextView zeekrListContactLastName, @NonNull TextView zeekrListContactPhone) {
    this.rootView = rootView;
    this.zeekrListContactAvatar = zeekrListContactAvatar;
    this.zeekrListContactFirstName = zeekrListContactFirstName;
    this.zeekrListContactLastName = zeekrListContactLastName;
    this.zeekrListContactPhone = zeekrListContactPhone;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrListItemContactMergeBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_list_item_contact_merge, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrListItemContactMergeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_list_contact_avatar;
      ImageView zeekrListContactAvatar = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactAvatar == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_first_name;
      TextView zeekrListContactFirstName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactFirstName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_last_name;
      TextView zeekrListContactLastName = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactLastName == null) {
        break missingId;
      }

      id = R.id.zeekr_list_contact_phone;
      TextView zeekrListContactPhone = ViewBindings.findChildViewById(rootView, id);
      if (zeekrListContactPhone == null) {
        break missingId;
      }

      return new ZeekrListItemContactMergeBinding(rootView, zeekrListContactAvatar,
          zeekrListContactFirstName, zeekrListContactLastName, zeekrListContactPhone);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
