// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textview.MaterialTextView;
import com.zeekr.component.R;
import com.zeekr.component.rebound.ZeekrReboundRefreshLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrDialogContentTextLayoutBinding implements ViewBinding {
  @NonNull
  private final ZeekrReboundRefreshLayout rootView;

  @NonNull
  public final MaterialTextView zeekrDialogConfirmContentText;

  private ZeekrDialogContentTextLayoutBinding(@NonNull ZeekrReboundRefreshLayout rootView,
      @NonNull MaterialTextView zeekrDialogConfirmContentText) {
    this.rootView = rootView;
    this.zeekrDialogConfirmContentText = zeekrDialogConfirmContentText;
  }

  @Override
  @NonNull
  public ZeekrReboundRefreshLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrDialogContentTextLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrDialogContentTextLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_dialog_content_text_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrDialogContentTextLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.zeekr_dialog_confirm_content_text;
      MaterialTextView zeekrDialogConfirmContentText = ViewBindings.findChildViewById(rootView, id);
      if (zeekrDialogConfirmContentText == null) {
        break missingId;
      }

      return new ZeekrDialogContentTextLayoutBinding((ZeekrReboundRefreshLayout) rootView,
          zeekrDialogConfirmContentText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
