// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.zeekr.component.R;
import com.zeekr.component.slider.ZeekrProgressBar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrPlayGroupLayoutBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final TextView exoDuration;

  @NonNull
  public final ImageView exoPlayPause;

  @NonNull
  public final TextView exoPosition;

  @NonNull
  public final ZeekrProgressBar exoProgress;

  @NonNull
  public final TextView exoSeparator;

  private ZeekrPlayGroupLayoutBinding(@NonNull View rootView, @NonNull TextView exoDuration,
      @NonNull ImageView exoPlayPause, @NonNull TextView exoPosition,
      @NonNull ZeekrProgressBar exoProgress, @NonNull TextView exoSeparator) {
    this.rootView = rootView;
    this.exoDuration = exoDuration;
    this.exoPlayPause = exoPlayPause;
    this.exoPosition = exoPosition;
    this.exoProgress = exoProgress;
    this.exoSeparator = exoSeparator;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrPlayGroupLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.zeekr_play_group_layout, parent);
    return bind(parent);
  }

  @NonNull
  public static ZeekrPlayGroupLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.exo_duration;
      TextView exoDuration = ViewBindings.findChildViewById(rootView, id);
      if (exoDuration == null) {
        break missingId;
      }

      id = R.id.exo_play_pause;
      ImageView exoPlayPause = ViewBindings.findChildViewById(rootView, id);
      if (exoPlayPause == null) {
        break missingId;
      }

      id = R.id.exo_position;
      TextView exoPosition = ViewBindings.findChildViewById(rootView, id);
      if (exoPosition == null) {
        break missingId;
      }

      id = R.id.exo_progress;
      ZeekrProgressBar exoProgress = ViewBindings.findChildViewById(rootView, id);
      if (exoProgress == null) {
        break missingId;
      }

      id = R.id.exo_separator;
      TextView exoSeparator = ViewBindings.findChildViewById(rootView, id);
      if (exoSeparator == null) {
        break missingId;
      }

      return new ZeekrPlayGroupLayoutBinding(rootView, exoDuration, exoPlayPause, exoPosition,
          exoProgress, exoSeparator);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
