// Generated by view binder compiler. Do not edit!
package com.zeekr.component.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import com.zeekr.component.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ZeekrToastGroupLayoutBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final MaterialCardView zeekrToastCard;

  @NonNull
  public final LinearLayout zeekrToastGroup;

  @NonNull
  public final ImageView zeekrToastIcon;

  @NonNull
  public final TextView zeekrToastMessage;

  private ZeekrToastGroupLayoutBinding(@NonNull MaterialCardView rootView,
      @NonNull MaterialCardView zeekrToastCard, @NonNull LinearLayout zeekrToastGroup,
      @NonNull ImageView zeekrToastIcon, @NonNull TextView zeekrToastMessage) {
    this.rootView = rootView;
    this.zeekrToastCard = zeekrToastCard;
    this.zeekrToastGroup = zeekrToastGroup;
    this.zeekrToastIcon = zeekrToastIcon;
    this.zeekrToastMessage = zeekrToastMessage;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ZeekrToastGroupLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ZeekrToastGroupLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.zeekr_toast_group_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ZeekrToastGroupLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      MaterialCardView zeekrToastCard = (MaterialCardView) rootView;

      id = R.id.zeekr_toast_group;
      LinearLayout zeekrToastGroup = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToastGroup == null) {
        break missingId;
      }

      id = R.id.zeekr_toast_icon;
      ImageView zeekrToastIcon = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToastIcon == null) {
        break missingId;
      }

      id = R.id.zeekr_toast_message;
      TextView zeekrToastMessage = ViewBindings.findChildViewById(rootView, id);
      if (zeekrToastMessage == null) {
        break missingId;
      }

      return new ZeekrToastGroupLayoutBinding((MaterialCardView) rootView, zeekrToastCard,
          zeekrToastGroup, zeekrToastIcon, zeekrToastMessage);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
